/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AnrkSaleContractInterface extends utils.Interface {
  functions: {
    "aNRK()": FunctionFragment;
    "approveBuyer(address)": FunctionFragment;
    "approveBuyers(address[])": FunctionFragment;
    "approvedBuyers(address)": FunctionFragment;
    "buyAlphaNRK(address,uint256)": FunctionFragment;
    "currencyOfPrice(address)": FunctionFragment;
    "getCurrencyOfPrice(address)": FunctionFragment;
    "initialize(address,address,uint256,address)": FunctionFragment;
    "initialized()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setANRKPrice(address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawTokens(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "aNRK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveBuyer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveBuyers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedBuyers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "buyAlphaNRK",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyOfPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyOfPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setANRKPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "aNRK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveBuyers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedBuyers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyAlphaNRK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyOfPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyOfPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setANRKPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "SaleEnded(address,uint256)": EventFragment;
    "SaleStarted(address,uint256)": EventFragment;
    "SellerApproval(address,address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleEnded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellerApproval"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type SaleEndedEvent = TypedEvent<
  [string, BigNumber],
  { activator: string; timestamp: BigNumber }
>;

export type SaleEndedEventFilter = TypedEventFilter<SaleEndedEvent>;

export type SaleStartedEvent = TypedEvent<
  [string, BigNumber],
  { activator: string; timestamp: BigNumber }
>;

export type SaleStartedEventFilter = TypedEventFilter<SaleStartedEvent>;

export type SellerApprovalEvent = TypedEvent<
  [string, string, string],
  { approver: string; seller: string; message: string }
>;

export type SellerApprovalEventFilter = TypedEventFilter<SellerApprovalEvent>;

export interface AnrkSaleContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AnrkSaleContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aNRK(overrides?: CallOverrides): Promise<[string]>;

    approveBuyer(
      newBuyer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approveBuyers(
      newBuyers_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approvedBuyers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    buyAlphaNRK(
      currency: string,
      amountPaid_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    currencyOfPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCurrencyOfPrice(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      aNRK_: string,
      currency: string,
      aNRKPrice_: BigNumberish,
      saleProceedsAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setANRKPrice(
      currency: string,
      newANRKPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawTokens(
      tokenToWithdraw_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  aNRK(overrides?: CallOverrides): Promise<string>;

  approveBuyer(
    newBuyer_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approveBuyers(
    newBuyers_: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approvedBuyers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  buyAlphaNRK(
    currency: string,
    amountPaid_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  currencyOfPrice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getCurrencyOfPrice(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    aNRK_: string,
    currency: string,
    aNRKPrice_: BigNumberish,
    saleProceedsAddress_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setANRKPrice(
    currency: string,
    newANRKPrice_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawTokens(
    tokenToWithdraw_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    aNRK(overrides?: CallOverrides): Promise<string>;

    approveBuyer(
      newBuyer_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    approveBuyers(
      newBuyers_: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approvedBuyers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    buyAlphaNRK(
      currency: string,
      amountPaid_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    currencyOfPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrencyOfPrice(
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      aNRK_: string,
      currency: string,
      aNRKPrice_: BigNumberish,
      saleProceedsAddress_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setANRKPrice(
      currency: string,
      newANRKPrice_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawTokens(
      tokenToWithdraw_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "SaleEnded(address,uint256)"(
      activator?: string | null,
      timestamp?: null
    ): SaleEndedEventFilter;
    SaleEnded(
      activator?: string | null,
      timestamp?: null
    ): SaleEndedEventFilter;

    "SaleStarted(address,uint256)"(
      activator?: string | null,
      timestamp?: null
    ): SaleStartedEventFilter;
    SaleStarted(
      activator?: string | null,
      timestamp?: null
    ): SaleStartedEventFilter;

    "SellerApproval(address,address,string)"(
      approver?: string | null,
      seller?: string | null,
      message?: string | null
    ): SellerApprovalEventFilter;
    SellerApproval(
      approver?: string | null,
      seller?: string | null,
      message?: string | null
    ): SellerApprovalEventFilter;
  };

  estimateGas: {
    aNRK(overrides?: CallOverrides): Promise<BigNumber>;

    approveBuyer(
      newBuyer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approveBuyers(
      newBuyers_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approvedBuyers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyAlphaNRK(
      currency: string,
      amountPaid_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    currencyOfPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrencyOfPrice(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      aNRK_: string,
      currency: string,
      aNRKPrice_: BigNumberish,
      saleProceedsAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setANRKPrice(
      currency: string,
      newANRKPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawTokens(
      tokenToWithdraw_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aNRK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approveBuyer(
      newBuyer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approveBuyers(
      newBuyers_: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approvedBuyers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyAlphaNRK(
      currency: string,
      amountPaid_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    currencyOfPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrencyOfPrice(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      aNRK_: string,
      currency: string,
      aNRKPrice_: BigNumberish,
      saleProceedsAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setANRKPrice(
      currency: string,
      newANRKPrice_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawTokens(
      tokenToWithdraw_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
